server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/frg_exng
    username: root
    password: koteczek123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    logging:
      level:
        org.hibernate.SQL: DEBUG
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: notification-group
      topic: new-currency
