version: '3.8'

services:
  # Mikroserwis Spring Boot
  app:
    image: my-spring-app:latest  # Zamień na właściwą nazwę obrazu
    build: .
    container_name: my-spring-app
    depends_on:
      - mysql
      - kafka  # Dodano zależność do Kafki
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/frg_exng
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: koteczek123!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093  # Dodano ustawienie dla Kafki
    ports:
      - "8080:8080"

  # MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frg_exng
      MYSQL_USER: admin
      MYSQL_PASSWORD: koteczek123!
    ports:
      - "3307:3307"  # Otwierasz port 3307, aby pasował do konfiguracji

  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_EXTERNAL_PORT: 9093
      KAFKA_LISTENER_INTERNAL_HOSTNAME: kafka
      KAFKA_LISTENER_EXTERNAL_HOSTNAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"  # Otwierasz port 9093, aby Kafkę można było używać z zewnątrz

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"  # Port Zookeepera

networks:
  default:
    driver: bridge
