version: '3.8'

services:
  # Mikroserwis Spring Boot
  app:
    image: my-rate-service:latest
    build: "./Rates Service"
    container_name: rate-service
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/frg_exng
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: koteczek123!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"

  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9093:9092"  # Port hosta:port wewnętrzny Kafki

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

networks:
  default:
    driver: bridge