server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3307/frg_exng
    username: root
    password: koteczek123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    logging:
      level:
        org.hibernate.SQL: DEBUG
  #  kafka:
  #    bootstrap-servers: kafka:9092
  #    consumer:
  #      group-id: my-group
  #      auto-offset-reset: earliest
  #    producer:
  #      retries: 3
  #      acks: all


